// Generated by FUECCode.verilog_encoder_module
module fuec_encoder_48_32 (
    input  wire [31:0] d,
    output wire [15:0] p,
    output wire [47:0] cw
);

    // Parity equations
    // parity bit p0 at cw[32]
    assign p[0] = d[2] ^ d[4] ^ d[9] ^ d[10] ^ d[11] ^ d[12] ^ d[13] ^ d[14] ^ d[15] ^ d[17] ^ d[18] ^ d[19] ^ d[20] ^ d[21] ^ d[24] ^ d[26] ^ d[29] ^ d[30] ^ d[31];
    // parity bit p1 at cw[33]
    assign p[1] = d[1] ^ d[2] ^ d[3] ^ d[4] ^ d[6] ^ d[9] ^ d[11] ^ d[15] ^ d[16] ^ d[22] ^ d[25] ^ d[26] ^ d[27] ^ d[29] ^ d[30];
    // parity bit p2 at cw[34]
    assign p[2] = d[1] ^ d[6] ^ d[7] ^ d[8] ^ d[10] ^ d[11] ^ d[12] ^ d[16] ^ d[17] ^ d[18] ^ d[20] ^ d[23] ^ d[24] ^ d[28] ^ d[29] ^ d[31];
    // parity bit p3 at cw[35]
    assign p[3] = d[0] ^ d[2] ^ d[3] ^ d[6] ^ d[8] ^ d[12] ^ d[13] ^ d[17] ^ d[18] ^ d[21] ^ d[24] ^ d[28] ^ d[29];
    // parity bit p4 at cw[36]
    assign p[4] = d[0] ^ d[1] ^ d[5] ^ d[6] ^ d[8] ^ d[9] ^ d[11] ^ d[12] ^ d[14] ^ d[17] ^ d[18] ^ d[20] ^ d[23] ^ d[25] ^ d[28] ^ d[30];
    // parity bit p5 at cw[37]
    assign p[5] = d[1] ^ d[3] ^ d[5] ^ d[9] ^ d[10] ^ d[12] ^ d[13] ^ d[14] ^ d[16] ^ d[18] ^ d[20] ^ d[22] ^ d[23] ^ d[26] ^ d[27] ^ d[28] ^ d[30];
    // parity bit p6 at cw[38]
    assign p[6] = d[2] ^ d[3] ^ d[5] ^ d[6] ^ d[9] ^ d[10] ^ d[11] ^ d[13] ^ d[14] ^ d[17] ^ d[19] ^ d[20] ^ d[21] ^ d[22] ^ d[23] ^ d[25] ^ d[27] ^ d[28] ^ d[29] ^ d[30] ^ d[31];
    // parity bit p7 at cw[39]
    assign p[7] = d[0] ^ d[2] ^ d[4] ^ d[5] ^ d[7] ^ d[8] ^ d[11] ^ d[13] ^ d[16] ^ d[17] ^ d[21] ^ d[22] ^ d[24] ^ d[26] ^ d[30];
    // parity bit p8 at cw[40]
    assign p[8] = d[1] ^ d[3] ^ d[5] ^ d[8] ^ d[9] ^ d[10] ^ d[11] ^ d[12] ^ d[14] ^ d[15] ^ d[17] ^ d[18] ^ d[19] ^ d[21] ^ d[22] ^ d[25] ^ d[26] ^ d[28] ^ d[30] ^ d[31];
    // parity bit p9 at cw[41]
    assign p[9] = d[0] ^ d[2] ^ d[3] ^ d[4] ^ d[5] ^ d[7] ^ d[8] ^ d[12] ^ d[13] ^ d[15] ^ d[20] ^ d[23] ^ d[27] ^ d[31];
    // parity bit p10 at cw[42]
    assign p[10] = d[0] ^ d[1] ^ d[3] ^ d[7] ^ d[9] ^ d[10] ^ d[12] ^ d[13] ^ d[15] ^ d[16] ^ d[17] ^ d[21] ^ d[23] ^ d[24] ^ d[28] ^ d[29] ^ d[30] ^ d[31];
    // parity bit p11 at cw[43]
    assign p[11] = d[2] ^ d[3] ^ d[4] ^ d[7] ^ d[8] ^ d[10] ^ d[12] ^ d[14] ^ d[17] ^ d[19] ^ d[20] ^ d[22] ^ d[23] ^ d[26] ^ d[27] ^ d[28] ^ d[29] ^ d[31];
    // parity bit p12 at cw[44]
    assign p[12] = d[3] ^ d[5] ^ d[6] ^ d[8] ^ d[9] ^ d[12] ^ d[13] ^ d[14] ^ d[15] ^ d[16] ^ d[19] ^ d[20] ^ d[21] ^ d[22] ^ d[24] ^ d[29];
    // parity bit p13 at cw[45]
    assign p[13] = d[3] ^ d[4] ^ d[5] ^ d[7] ^ d[9] ^ d[11] ^ d[16] ^ d[19] ^ d[20] ^ d[23] ^ d[24] ^ d[25] ^ d[26] ^ d[30];
    // parity bit p14 at cw[46]
    assign p[14] = d[1] ^ d[2] ^ d[5] ^ d[8] ^ d[10] ^ d[11] ^ d[12] ^ d[16] ^ d[17] ^ d[19] ^ d[21] ^ d[22] ^ d[24] ^ d[25] ^ d[26] ^ d[28] ^ d[31];
    // parity bit p15 at cw[47]
    assign p[15] = d[1] ^ d[2] ^ d[4] ^ d[5] ^ d[7] ^ d[9] ^ d[10] ^ d[14] ^ d[19] ^ d[22] ^ d[24] ^ d[26] ^ d[28] ^ d[29] ^ d[30];

    // Codeword assembly
    assign cw[0] = d[0];
    assign cw[1] = d[1];
    assign cw[2] = d[2];
    assign cw[3] = d[3];
    assign cw[4] = d[4];
    assign cw[5] = d[5];
    assign cw[6] = d[6];
    assign cw[7] = d[7];
    assign cw[8] = d[8];
    assign cw[9] = d[9];
    assign cw[10] = d[10];
    assign cw[11] = d[11];
    assign cw[12] = d[12];
    assign cw[13] = d[13];
    assign cw[14] = d[14];
    assign cw[15] = d[15];
    assign cw[16] = d[16];
    assign cw[17] = d[17];
    assign cw[18] = d[18];
    assign cw[19] = d[19];
    assign cw[20] = d[20];
    assign cw[21] = d[21];
    assign cw[22] = d[22];
    assign cw[23] = d[23];
    assign cw[24] = d[24];
    assign cw[25] = d[25];
    assign cw[26] = d[26];
    assign cw[27] = d[27];
    assign cw[28] = d[28];
    assign cw[29] = d[29];
    assign cw[30] = d[30];
    assign cw[31] = d[31];
    assign cw[32] = p[0];
    assign cw[33] = p[1];
    assign cw[34] = p[2];
    assign cw[35] = p[3];
    assign cw[36] = p[4];
    assign cw[37] = p[5];
    assign cw[38] = p[6];
    assign cw[39] = p[7];
    assign cw[40] = p[8];
    assign cw[41] = p[9];
    assign cw[42] = p[10];
    assign cw[43] = p[11];
    assign cw[44] = p[12];
    assign cw[45] = p[13];
    assign cw[46] = p[14];
    assign cw[47] = p[15];

endmodule