// Generated by FUECCode.verilog_encoder_module
module fuec_encoder_13_5 (
    input  wire [7:0] d,
    output wire [4:0] p,
    output wire [12:0] cw
);

    // Parity equations
    // parity bit p0 at cw[8]
    assign p[0] = d[0] ^ d[1] ^ d[3] ^ d[4] ^ d[6] ^ d[7];
    // parity bit p1 at cw[9]
    assign p[1] = d[1] ^ d[5] ^ d[6] ^ d[7];
    // parity bit p2 at cw[10]
    assign p[2] = d[0] ^ d[1] ^ d[2] ^ d[3] ^ d[5];
    // parity bit p3 at cw[11]
    assign p[3] = d[0] ^ d[3] ^ d[5] ^ d[6] ^ d[7];
    // parity bit p4 at cw[12]
    assign p[4] = d[0] ^ d[1] ^ d[2] ^ d[4] ^ d[6];

    // Codeword assembly
    assign cw[0] = d[0];
    assign cw[1] = d[1];
    assign cw[2] = d[2];
    assign cw[3] = d[3];
    assign cw[4] = d[4];
    assign cw[5] = d[5];
    assign cw[6] = d[6];
    assign cw[7] = d[7];
    assign cw[8] = p[0];
    assign cw[9] = p[1];
    assign cw[10] = p[2];
    assign cw[11] = p[3];
    assign cw[12] = p[4];

endmodule